name: Tourism Project Pipeline

on:
  push:
    branches: [ "main" ]      # re-run on every push to main
  workflow_dispatch:          # allow manual runs

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN_TPP }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10", cache: "pip" }
      - name: Install CI requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ci_requirements.txt
      - name: Upload raw dataset to HF
        run: |
          python tourism_project/model_building/data_register.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN_TPP }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10", cache: "pip" }
      - name: Install CI requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ci_requirements.txt
      - name: Run data preparation (clean/split/publish)
        run: |
          python tourism_project/model_building/data_prep.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN_TPP }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10", cache: "pip" }
      - name: Install CI requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ci_requirements.txt
      - name: Train, evaluate, and register model
        run: |
          python tourism_project/model_building/train.py

  deploy-hosting:
    needs: [ model-training, data-prep, register-dataset ]
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN_TPP }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10", cache: "pip" }
      - name: Install CI requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ci_requirements.txt
      - name: Push Streamlit app to HF Space
        run: |
          python tourism_project/deployment/push_space.py
